// <auto-generated />
using Haengma.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Haengma.GS.Migrations
{
    [DbContext(typeof(HaengmaContext))]
    partial class HaengmaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Haengma.Core.Persistence.Models.InternalGame", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BlackPlayer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BoardSize")
                        .HasColumnType("int");

                    b.Property<int>("ByoYomiPeriods")
                        .HasColumnType("int");

                    b.Property<int>("ByoYomiSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ColorDecision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Handicap")
                        .HasColumnType("int");

                    b.Property<double>("Komi")
                        .HasColumnType("float");

                    b.Property<int>("MainTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Sgf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeSettingsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhitePlayer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
