// <auto-generated />
using System;
using Haengma.Backend.Imperative.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Haengma.GS.Migrations
{
    [DbContext(typeof(HaengmaContext))]
    partial class HaengmaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Haengma.Backend.Imperative.Persistance.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Black")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sgf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("White")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Black");

                    b.HasIndex("White");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Haengma.Backend.Imperative.Persistance.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Haengma.Backend.Imperative.Persistance.Models.Game", b =>
                {
                    b.HasOne("Haengma.Backend.Imperative.Persistance.Models.User", null)
                        .WithMany()
                        .HasForeignKey("Black")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Haengma.Backend.Imperative.Persistance.Models.User", null)
                        .WithMany()
                        .HasForeignKey("White")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
