name: Publish package to GitHub
on:
  release:
    types: [created]
jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Gradle publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_ACTOR: ${{ secrets.PUBLISH_USER }}
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}